### ISSUE TITLE
Fix 'Moment'/Date deprecation in InfoBanner

### ISSUE THREAD

**Issue by AndyEPhipps** [comicrelief/component-library#153]
```
10:11:14 AM: Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
10:11:14 AM: Arguments:
10:11:14 AM: [0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: en, _i: 7 March 2019, _f: null, _strict: undefined, _locale: [object Object]
10:11:14 AM: Error
10:11:14 AM:     at Function.createFromInputFallback (/opt/build/repo/public/render-page.js:26789:98)
10:11:14 AM:     at configFromString (/opt/build/repo/public/render-page.js:28854:15)
10:11:14 AM:     at configFromInput (/opt/build/repo/public/render-page.js:29080:13)
10:11:14 AM:     at prepareConfig (/opt/build/repo/public/render-page.js:29063:13)
10:11:14 AM:     at createFromConfig (/opt/build/repo/public/render-page.js:29030:44)
10:11:14 AM:     at createLocalOrUTC (/opt/build/repo/public/render-page.js:29117:16)
10:11:14 AM:     at createLocal (/opt/build/repo/public/render-page.js:29121:16)
10:11:14 AM:     at Function.hooks [as globalMoment] (/opt/build/repo/public/render-page.js:26481:29)
10:11:14 AM:     at Function.value (/opt/build/repo/public/render-page.js:49819:16919)
10:11:14 AM:     at t.value (/opt/build/repo/public/render-page.js:49819:17653)
10:11:14 AM:     at t.value (/opt/build/repo/public/render-page.js:49819:17027)
10:11:14 AM:     at c (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:37:337)
10:11:14 AM:     at Ua (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
10:11:14 AM:     at a.render (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:48)
10:11:14 AM:     at a.read (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:161)
10:11:14 AM:     at renderToString (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:55:83)

```

**Comment by lebaz20** [comment]
Fixed by #162
